apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: auth-ms
  name: auth-ms
spec:
  ports:
  - name: "3006"
    port: 3006
    protocol: TCP
    targetPort: 3006
  selector:
    app: auth-ms    
  type: ClusterIP
status:
  loadBalancer: {}
