apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: client-gateway
  name: client-gateway
spec:
  ports:
  - name: "3005"
    port: 3005
    protocol: TCP
    targetPort: 3005
  selector:
    app: client-gateway
  type: NodePort
status:
  loadBalancer: {}
